horizontal WW15 rebase conflict resolution
projectceladon/vendor-intel-utils-vertical-iot pull request #59
Opened 2023-04-19 10:30 UTC by pchenthx1

removal of redundant commits causing conflicts

Tracked-On: OAM-108876

2023-04-19 18:32 UTC, pchenthx1 commented on bsp_diff/caas/hardware/intel/external/mesa3d-intel/0005-Add-missing-ADL-device-ID.patch
This is superseded by b03c0b5d30bd (OAM-106859)

2023-04-19 18:35 UTC, pchenthx1 commented on bsp_diff/caas/hardware/intel/external/minigbm-intel/0005-Handle-DRM_IOCTL_I915_GEM_MMAP_GTT-failure-for-VF.patch
This is superseded by 3b02133f (OAM-106982)

2023-04-19 18:36 UTC, pchenthx1 commented
Reviewers: @basilchew @bnkoppad kindly review

2023-04-20 02:39 UTC, basilchew requested changes

2023-04-20 02:39 UTC, basilchew commented on bsp_diff/caas/hardware/intel/external/mesa3d-intel/0005-Add-missing-ADL-device-ID.patch
The state of OAM-106859 is still "in-progress".
Please check

2023-04-20 08:34 UTC, pchenthx1 commented on bsp_diff/caas/hardware/intel/external/mesa3d-intel/0005-Add-missing-ADL-device-ID.patch
It appeas that this patch is directly pushed into the repository instead of going through PR review process... https://github.com/projectceladon/external-mesa/commit/b03c0b5d30bd3ce22fe04265046721f640ce377a 

I notified He, Yue and updated the Jira ticket

2023-04-21 04:42 UTC, basilchew approved these changes

2023-05-13 04:54 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_vertical-preintegration/builds/172

Done by "Balaji, NirmalX" <nirmalx.balaji@intel.com>

2023-05-13 04:55 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_vertical-premerge/builds/82

Done by "Balaji, NirmalX" <nirmalx.balaji@intel.com>

2023-05-13 15:02 UTC, merged

2023-05-13 15:03 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Balaji, NirmalX" <nirmalx.balaji@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_vertical-mergerequest/builds/96