Clang fix for Android-S
projectceladon/vendor-intel-utils-vertical-iot pull request #74
Opened 2023-07-04 11:14 UTC by vdanix

2023-07-04 14:34 UTC, bnkoppad requested changes

2023-07-04 14:34 UTC, bnkoppad commented on bsp_diff/caas/hardware/intel/external/drm-intel/0002-Clang-fix-for-drm-intel.patch
> ++				if(bo_fake->block->virtual!=NULL)
Add (bo_fake->block !=NULL) also

2023-07-04 14:34 UTC, bnkoppad commented on bsp_diff/caas/hardware/intel/external/drm-intel/0002-Clang-fix-for-drm-intel.patch
> ++	if (bo_fake->block!=NULL)
Can **bo_fake->block->mem** variable be NULL ?

2023-07-04 14:34 UTC, bnkoppad commented on bsp_diff/caas/hardware/intel/external/media/mod/0001-Clang-fix-for-media_driver.patch
> ++                    && (pSurfaceEntries[0]->bAVS != NULL && pSurfaceEntries[0]->bAVS))
(pSurfaceEntries[0] != NULL && pSurfaceEntries[0]->bAVS)

2023-07-04 14:34 UTC, bnkoppad commented on bsp_diff/caas/hardware/intel/external/media/mod/0001-Clang-fix-for-media_driver.patch
> ++	    if(StoreRenderParams.pTarget[0]->b16UsrPtr !=NULL)
(pRenderParams->pTarget[0] != NULL && pRenderParams->pTarget[0]->b16UsrPtr !=NULL)

2023-07-04 14:34 UTC, bnkoppad commented on bsp_diff/caas/hardware/intel/external/media/mod/0001-Clang-fix-for-media_driver.patch
> +             pRenderParams->pTarget[0]            = StoreRenderParams.pTarget[0];
if(pRenderParams != NULL) {


}

2023-07-04 14:34 UTC, bnkoppad commented on bsp_diff/caas/hardware/intel/external/media/mod/0001-Clang-fix-for-media_driver.patch
> ++    if (pRenderingData->iLayers > 0 && pRenderingData->pLayers[0]->bIEF !=NULL)
pRenderingData ?

2023-07-04 14:34 UTC, bnkoppad commented on bsp_diff/caas/hardware/intel/external/media/mod/0001-Clang-fix-for-media_driver.patch
> ++    if (pRenderingData->iLayers > 0 && pRenderingData->pLayers[0]->bIEF != NULL)
pRenderingData ? check at all places

2023-07-10 01:48 UTC, feijiang1 approved these changes
LGTM
But need add Tracked-On jira number

2023-07-11 10:44 UTC, vdanix commented
> LGTM But need add Tracked-On jira number

Tracked-On added

2023-07-12 07:47 UTC, feijiang1 approved these changes
LGTM

2023-07-18 09:19 UTC, bnkoppad approved these changes

2023-07-20 05:44 UTC, vdanix commented
@basilchew please review the pr

2023-07-20 06:15 UTC, basilchew commented
Is there a corresponding PR or Jira for horizontal?

2023-07-20 06:38 UTC, vdanix commented
> Is there a corresponding PR or Jira for horizontal?

Horizontal jira : OAM-111281
Vertical revert jira : OAM-111282

2023-07-20 07:05 UTC, basilchew approved these changes

2023-07-20 08:31 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_vertical-preintegration/builds/185

2023-07-20 13:07 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_vertical-preintegration/builds/186

Done by "Dani, VishwanathX" <vishwanathx.dani@intel.com>

2023-07-20 13:07 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_vertical-premerge/builds/91

Done by "Dani, VishwanathX" <vishwanathx.dani@intel.com>

2023-07-20 17:50 UTC, merged

2023-07-20 17:51 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Dani, VishwanathX" <vishwanathx.dani@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_vertical-mergerequest/builds/106