[Config] disable fw cache config
projectceladon/vendor-intel-utils-vertical-iot pull request #8
Opened 2022-12-20 10:28 UTC by bkothapx

as per vts kernel compatablity test suit
test case is expecting CONFIG_FW_CACHE to n
config CONFIG_FW_CACHE, value = y but required n

Tracked-On: OAM-105308
Signed-off-by: vdanix <vishwanathx.dani@intel.com>
Signed-off-by: Kothapeta, BikshapathiX <bikshapathix.kothapeta@intel.com>

2022-12-29 07:29 UTC, JeevakaPrabu requested changes
please do the changes and raise the PR in https://github.com/projectceladon/device-androidia-mixins project itself

2022-12-30 06:37 UTC, zhuopeng-sg approved these changes

2022-12-30 07:44 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_rmr0_vertical-preintegration/builds/254

2023-01-02 05:44 UTC, bnkoppad approved these changes

2023-01-03 03:17 UTC, XiaoHeSG approved these changes

2023-01-03 16:16 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_rmr0_vertical-preintegration/builds/255

Done by "Mishra, ManishX" <manishx.mishra@intel.com>

2023-01-03 16:24 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests Triggered: CIT-CIV-CML-R(cml_nuc:caas - userdebug)

More details, logs, and binaries: /absp/builders/celadon_rmr0_vertical-premerge/builds/104

2023-01-03 17:25 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_rmr0_vertical-premerge/builds/105

Done by "Mishra, ManishX" <manishx.mishra@intel.com>

2023-01-04 07:51 UTC, merged

2023-01-04 07:52 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Mishra, ManishX" <manishx.mishra@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_rmr0_vertical-mergerequest/builds/105