Fix TPM error failure fix for NVIndex failure
projectceladon/vendor-intel-utils-vertical-iot pull request #82
Opened 2023-08-17 14:13 UTC by bkothapx

Multi Android VM support TPM error failure fix for NVIndex failure

Tracked-On: OAM-111783

2023-08-18 04:30 UTC, prashanth-intel approved these changes

2023-08-21 01:23 UTC, basilchew approved these changes

2023-08-21 01:25 UTC, basilchew requested changes
1) Have we tested this with non-secure boot loader?
2) What if the OVMF.fd file does not exists for the copy operation?

2023-08-21 05:40 UTC, bkothapx commented
> 1. Have we tested this with non-secure boot loader?
> 2. What if the OVMF.fd file does not exists for the copy operation?

update the patch adding changes handling above
verified with/without secure boot VM launch no issues observed

2023-08-21 05:41 UTC, prashanth-intel approved these changes

2023-08-21 06:18 UTC, basilchew approved these changes

2023-08-21 12:35 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_vertical-preintegration/builds/201

Done by "Sivaramakrishnan, UdhayanX" <udhayanx.sivaramakrishnan@intel.com>

2023-08-21 17:55 UTC, merged

2023-08-21 17:55 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Sivaramakrishnan, UdhayanX" <udhayanx.sivaramakrishnan@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_vertical-mergerequest/builds/111