Include sample encode/decode files in image
projectceladon/vendor-intel-utils-vertical-iot pull request #91
Opened 2023-09-20 07:24 UTC by prashanth-intel

Include sample encode/decode files in vendor image.

Tracked-On: OAM-112315

2023-09-20 09:59 UTC, bnkoppad approved these changes

2023-09-21 04:34 UTC, bnkoppad requested changes
Please share validation results.

2023-10-05 08:46 UTC, bnkoppad approved these changes

2023-10-09 01:28 UTC, basilchew approved these changes

2023-10-09 14:13 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_vertical-preintegration/builds/212

Done by "Arigela, LokeshX" <lokeshx.arigela@intel.com>

2023-10-09 14:17 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_vertical-premerge/builds/104

Done by "Arigela, LokeshX" <lokeshx.arigela@intel.com>

2023-10-09 20:06 UTC, merged

2023-10-09 20:06 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Arigela, LokeshX" <lokeshx.arigela@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_vertical-mergerequest/builds/122